In [70]:
import numpy as np

In [73]:
arr7 = np.arange(start=1,stop=20,step=3)
print(arr7)

[ 1  4  7 10 13 16 19]


In [68]:
a=[1,2,3,4,5,6,7,8,9]
print("a------%s" % a)
print("a[4]------%s" % a[4])
print("a[-2]------%s" % a[-2])
print("a[:4]------%s" % a[:4])
print("a[4:]------%s" % a[4:])
print("a[2:4]------%s" % a[2:4])
print("a[4:-2]------%s" % a[4:-2])


a------[1, 2, 3, 4, 5, 6, 7, 8, 9]
a[4]------5
a[-2]------8
a[:4]------[1, 3]
a[4:]------[5, 6, 7, 8, 9]
a[2:4]------[3, 4]
a[4:-2]------[5, 6, 7]


In [50]:
import akshare as ak
stock_zh_index_daily_df = ak.stock_zh_index_daily(symbol="sh000001")
print("准备数据-上证指数-表格形式")
print(stock_zh_index_daily_df)

准备数据-上证指数-表格形式
            date      open      high       low     close       volume
0     1990-12-19    96.050    99.980    95.790    99.980       126000
1     1990-12-20   104.300   104.390    99.980   104.390        19700
2     1990-12-21   109.070   109.130   103.730   109.130         2800
3     1990-12-24   113.570   114.550   109.130   114.550         3200
4     1990-12-25   120.090   120.250   114.550   120.250         1500
...          ...       ...       ...       ...       ...          ...
7869  2023-03-08  3271.880  3283.248  3263.693  3283.248  26044354700
7870  2023-03-09  3285.943  3289.060  3260.000  3276.094  26402185900
7871  2023-03-10  3255.512  3262.147  3229.496  3230.077  28113541000
7872  2023-03-13  3228.124  3268.696  3228.124  3268.696  29492808700
7873  2023-03-14  3261.922  3262.003  3216.993  3245.312  31990603300

[7874 rows x 6 columns]


In [51]:
sh000001=stock_zh_index_daily_df.to_numpy()
print("上证指数-转为Numpy")
print(sh000001)

上证指数-转为Numpy
[[datetime.date(1990, 12, 19) 96.05 99.98 95.79 99.98 126000]
 [datetime.date(1990, 12, 20) 104.3 104.39 99.98 104.39 19700]
 [datetime.date(1990, 12, 21) 109.07 109.13 103.73 109.13 2800]
 ...
 [datetime.date(2023, 3, 10) 3255.512 3262.147 3229.496 3230.077
  28113541000]
 [datetime.date(2023, 3, 13) 3228.124 3268.696 3228.124 3268.696
  29492808700]
 [datetime.date(2023, 3, 14) 3261.922 3262.003 3216.993 3245.312
  31990603300]]


In [54]:
sh000001=stock_zh_index_daily_df.to_numpy()
sh000001=sh000001[0,:]
print("上证指数-第1行")
print(sh000001)

上证指数-第1行
[datetime.date(1990, 12, 19) 96.05 99.98 95.79 99.98 126000]


In [53]:
sh000001=stock_zh_index_daily_df.to_numpy()
sh000001=sh000001[:,2]
print("上证指数-第2列")
print(sh000001)

上证指数-第2列
[99.98 104.39 109.13 ... 3262.147 3268.696 3262.003]


In [43]:
sh000001=sh000001[:,1:]
print("上证指数-删除时间列")
print(sh000001)

上证指数-删除时间列
[[96.05 99.98 95.79 99.98 126000]
 [104.3 104.39 99.98 104.39 19700]
 [109.07 109.13 103.73 109.13 2800]
 ...
 [3255.512 3262.147 3229.496 3230.077 28113541000]
 [3228.124 3268.696 3228.124 3268.696 29492808700]
 [3261.922 3262.003 3216.993 3245.312 31990603300]]


In [41]:
print("平均值："+str(sh000001.mean()))

平均值：1962080814.3542993
